timeout=100
default=archpower_install_xenon

archpower_install_xenon="dvd0:/arch/boot/ppc/vmlinuz-linux-xenon arch=ppc archisobasedir=arch archisolabel=ARCH_202606 initrd=dvd0:/arch/boot/ppc/initramfs-linux-xenon.img coherent_pool=16M read-only"

archpower_install_xenon_usb="uda1:/arch/boot/ppc/vmlinuz-linux-xenon arch=ppc archisobasedir=arch archisolabel=ARCH initrd=uda1:/arch/boot/ppc/initramfs-linux-xenon.img coherent_pool=16M read-only"
