timeout=100
default=archpower_install_ps3

archpower_install_ps3="/arch/boot/ppc/vmlinuz-linux-ps3 quiet arch=ppc archisobasedir=arch archisolabel=ARCH_202203 initrd=/arch/boot/ppc/initramfs-linux-ps3.img read-only"
archpower_install_xenon="dvd0:/arch/boot/ppc/vmlinuz-linux-xenon quiet arch=ppc archisobasedir=arch archisolabel=ARCH_202203 initrd=dvd0:/arch/boot/ppc/initramfs-linux-xenon.img coherent_pool=16M read-only"
